http://localhost:3000/people
  
###

GET  http://localhost:3000/people/20

###

POST http://localhost:3000/people HTTP/1.1
Content-Type: application/json

{
    "nome": "lol"
}

###

PUT  http://localhost:3000/people/19 HTTP/1.1
Content-Type: application/json

{
    "desc": "novo22",
    "teorema_id": "id2"
}

###

DELETE  http://localhost:3000/people/9 HTTP/1.1
